server:
  servlet:
    context-path: /springai
spring:
  ai:
    openai:
      api-key: ${OPENAI_KEY}
      chat:
        options:
          model: gpt-4.1 #gpt-4.1, gpt-4o
          temperature: 0.7
          max-completion-tokens: 2000
logging:
  level:
    org:
      springframework:
        ai.chat.client.advisor.SimpleLoggerAdvisor: DEBUG

weather:
  api-key : 
  api-url : http://api.weatherapi.com/v1

currency-exchange:
  api-key :
  base-url: https://openexchangerates.org/api

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
      base-path: /actuator
  endpoint:
    prometheus:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
        step: 5s
  metrics:
    distribution:
      percentiles-histogram:
        all: true
    enable:
      all: true
  tracing:
    sampling:
      probability: 1.0
    enabled: true
