server:
  servlet:
    context-path: /springai

logging:
  level:
    org:
      springframework:
        ai.chat.client.advisor.SimpleLoggingAdvisor: DEBUG
weather:
  api-key :
  api-url : http://api.weatherapi.com/v1

currency-exchange:
  api-key :
  base-url: https://openexchangerates.org/api